
# Default lab org and location name
#   - Each lab will start at the domain scope under this org and location
lab_org_name: "Lab Organization"
lab_location_name: "Lab Location"

openstack_domain_name: "labs-domain"
openstack_domain_desc: "Shared LAB Project"
openstack_project_name: "labs-project"
openstack_project_desc: "Shared Lab Project"
openstack_project_admin_user: "labs-admin"
openstack_project_admin_pass: "changeme"
openstack_project_admin_desc: "LABS Domain Admin User"
openstack_project_admin_email: "shannon.mitchell@rackspace.com"


foreman_operating_systems:
  - name: "ubuntu-xenial"
    description: "Ubuntu Xenial"
    family: Debian
    major: 16
    minor: 04
    password_hash: SHA256
    release_name: 'xenial'
    architectures:
      - x86_64
  - name: "ubuntu-bionic"
    description: "Ubuntu Bionic"
    family: Debian
    major: 18
    minor: 04
    password_hash: SHA256
    release_name: 'bionic'
    architectures:
      - x86_64



provisioning_template_path: "{{ role_path }}/files/provisioning_templates"


foreman_settings:
  - key: "safemode_render"
    value: false

foreman_global_parameters:
  - key: "foreman_server_ip"
    value: '{{ katello_host_ip }}'

