---
- name: Update CA Trust
  shell: update-ca-trust

- name: Restart foreman-proxy
  service:
    name: foreman-proxy
    state: restarted

- name: Fix hook permissions
  shell: |
    find /usr/share/foreman/config/hooks/ -type f -exec chmod 755 {} \;
    restorecon -RvF /usr/share/foreman/config/hooks

- name: Restart httpd
  service:
    name: httpd
    state: restarted
