#####################################
# libvirt provisioning network config
#####################################
provisioning_name: "provisioning"
provisioning_netmask: "255.255.252.0"
provisioning_network_cidr: "172.0.60.0/22"
provisioning_gateway_ip: "172.0.60.1"       
provisioning_range_start: "172.0.60.101"
provisioning_range_end: "172.0.63.254"

#############################################
# General openstack network configs
# separate from mnaio libvirt settings.
# differs based on the lab environment. 
#############################################
external_controller_ips:
  - 172.0.60.20
  - 172.0.60.21
  - 172.0.60.22
external_network_cidr: "{{ provisioning_network_cidr }}"
external_network_gateway: "{{ provisioning_gateway_ip }}"
external_floating_ip: 172.0.60.100


# Each environment's network is different. (used to decide which custom-nic templates to use for rpcr)
lab_network_environment: "mnaio"

# Each environment may have a different disk layout and config. 
# We are using this to decide which template to render.
lab_ceph_config: "mnaio_storage_layout"


##########################################
# Org and Location that holds the labs
# The labs are defined with domains
##########################################
lab_org_name: "Lab Organization"
lab_location_name: "Lab Location"


#######################
# Base domain name
#######################
lab_base_domain_name: "mnaio.rpc.rackspace.com"

##################
# Base image path
##################
base_image_path: "/var/lib/libvirt/images"


###################################
# Default lab server root password
###################################
instance_admin_pass: "changeme"


###############################################################
# Set up some global parameters to be used for domain creation
###############################################################

additional_foreman_global_parameters:
  - key: "lab_org_name"
    value: '{{ lab_org_name }}'
  - key: "lab_location_name"
    value: '{{ lab_location_name }}'
  - key: "lab_base_domain_name"
    value: '{{ lab_base_domain_name }}'
  - key: "multicast_group_base"
    value: "239.1.33"
  - key: "vxlan_network_prefix"
    value: "172.22"
  - key: "vxlan_netmask"
    value: "255.255.252.0"
  - key: "vxlan_third_octet_step"
    value: 4
  - key: "vxlan_networks"
    value: "mgmt,stor-mgmt,storage,tenant,lbaas,inside-net,gw-net"

################
# List of users
################
foreman_users:
  - username: labadmin
    password: "{{ instance_admin_pass }}"
    mail: shannon.mitchell@rackspace.com
    admin: yes
    default_organization: '{{ lab_org_name }}'
    default_location: '{{ lab_location_name }}'
    description: "Lab Admin"
    firstname: Lab
    lastname: Admin


#######################################
# Openstack project used for instances
#######################################

openstack_domain_name: "default"
openstack_domain_desc: "Shared LAB Project"
openstack_project_name: "labs-project"
openstack_project_desc: "Shared Lab Project"
openstack_project_admin_user: "labs-admin"
openstack_project_admin_pass: "{{ instance_admin_pass }}"
openstack_project_admin_desc: "LABS Domain Admin User"
openstack_project_admin_email: "shannon.mitchell@rackspace.com"

    
########################################################
# For vlans on ironic nodes, we will have to have a way
# to pre-define and check-in/check-out the static labs.
# The static labs, are just a collection of VLANS and 
# networks set up by netsec that is shared across all 
# ironic nodes in the phobos cluster.
########################################################
static_labs:
  - domain_name: "lab1.{{ lab_base_domain_name }}"
    domain_organizations: 
      - '{{ lab_org_name }}'
    domain_locations:
      - '{{ lab_location_name }}'
    domain_description: "LAB1 Static Domain"
    domain_parameters:
      - name: "type"
        value: "vlan"
        parameter_type: "string"
      - name: "in-use"
        value: "no"
        parameter_type: "string"
      - name: "internal_floating_ip"
        value: "172.0.64.10"
        parameter_type: "string"
      - name: "internal_vrid"
        value: "12"
        parameter_type: "string"
      - name: "external_vrid"
        value: "13"
        parameter_type: "string"
    domain_subnets:
      - subnet_name: "LAB1-MGMT"
        subnet_description: "LAB1 management network with static VLANs"
        subnet_vlan: 201
        subnet_type: "IPv4"
        subnet_network: "172.0.64.0"
        subnet_mask: "255.255.252.0"
        subnet_ipam: "Random DB"
        subnet_dhcp_from: "172.0.64.50"
        subnet_dhcp_to: "172.0.64.254"
        subnet_gateway: "172.0.64.1"
        subnet_bootmode: "Static"
      - subnet_name: "LAB1-STOR-MGMT"
        subnet_description: "LAB1 storage management network with static VLANs"
        subnet_vlan: 202
        subnet_type: "IPv4"
        subnet_network: "172.0.68.0"
        subnet_mask: "255.255.252.0"
        subnet_ipam: "Random DB"
        subnet_dhcp_from: "172.0.68.50"
        subnet_dhcp_to: "172.0.68.254"
        subnet_gateway: "172.0.68.1"
        subnet_bootmode: "Static"
      - subnet_name: "LAB1-STORAGE"
        subnet_description: "LAB1 storage network with static VLANs"
        subnet_vlan: 203
        subnet_type: "IPv4"
        subnet_network: "172.0.72.0"
        subnet_mask: "255.255.252.0"
        subnet_ipam: "Random DB"
        subnet_dhcp_from: "172.0.72.50"
        subnet_dhcp_to: "172.0.72.254"
        subnet_gateway: "172.0.72.1"
        subnet_bootmode: "Static"
      - subnet_name: "LAB1-TENANT"
        subnet_description: "LAB1 tenant network with static VLANs"
        subnet_vlan: 204
        subnet_type: "IPv4"
        subnet_network: "172.0.76.0"
        subnet_mask: "255.255.252.0"
        subnet_ipam: "Random DB"
        subnet_dhcp_from: "172.0.76.50"
        subnet_dhcp_to: "172.0.76.254"
        subnet_gateway: "172.0.76.1"
        subnet_bootmode: "Static"
      - subnet_name: "LAB1-LBAAS"
        subnet_description: "LAB1 lbaas network with static VLANs"
        subnet_vlan: 205
        subnet_type: "IPv4"
        subnet_network: "172.0.80.0"
        subnet_mask: "255.255.252.0"
        subnet_ipam: "Random DB"
        subnet_dhcp_from: "172.0.80.50"
        subnet_dhcp_to: "172.0.80.254"
        subnet_gateway: "172.0.80.1"
        subnet_bootmode: "Static"
      - subnet_name: "LAB1-INSIDE-NET"
        subnet_description: "LAB1 inside net network with static VLANs"
        subnet_vlan: 206
        subnet_type: "IPv4"
        subnet_network: "172.0.84.0"
        subnet_mask: "255.255.252.0"
        subnet_ipam: "Random DB"
        subnet_dhcp_from: "172.0.84.50"
        subnet_dhcp_to: "172.0.84.254"
        subnet_gateway: "172.0.84.1"
        subnet_bootmode: "Static"
      - subnet_name: "LAB1-GW-NET"
        subnet_description: "LAB1 gateway net network with static VLANs"
        subnet_vlan: 207
        subnet_type: "IPv4"
        subnet_network: "172.0.88.0"
        subnet_mask: "255.255.252.0"
        subnet_ipam: "Random DB"
        subnet_dhcp_from: "172.0.88.50"
        subnet_dhcp_to: "172.0.88.254"
        subnet_gateway: "172.0.88.1"
        subnet_bootmode: "Static"
      - subnet_name: "LAB1-MANILLA"
        subnet_description: "LAB1 Manilla network with static VLANs"
        subnet_vlan: 208
        subnet_type: "IPv4"
        subnet_network: "172.0.92.0"
        subnet_mask: "255.255.252.0"
        subnet_ipam: "Random DB"
        subnet_dhcp_from: "172.0.92.50"
        subnet_dhcp_to: "172.0.92.254"
        subnet_gateway: "172.0.92.1"
        subnet_bootmode: "Static"


#############################################################
# Variables to set up the compute profile to allow the
# foreman to spin up instances in the libvirt environment
#############################################################

foreman_compute_resources_libvirt:
  - name: "libvirt-mnaio"
    provider: "libvirt"
    url: "qemu+ssh://root@{{ katello_host_ip }}/system"
    organizations: 
      - '{{ lab_org_name }}'
    locations: 
      - '{{ lab_location_name }}'
    description: "Local Libvirt Instance"
    provisioning_subnet:
      subnet_name: "MNAIO-PROV"
      subnet_description: "MNAIO provisioning subnet"
      subnet_type: "IPv4"
      subnet_network: "{{ provisioning_network_cidr.split('/')[0] }}"
      subnet_mask: "{{ provisioning_netmask }}"
      subnet_ipam: "Random DB"
      subnet_dhcp_from: "{{ provisioning_range_start }}"
      subnet_dhcp_to: "{{ provisioning_range_end }}"
      subnet_gateway: "{{ provisioning_gateway_ip }}"
      subnet_bootmode: "DHCP"
      subnet_domains:
	- "openstacklocal"
        - "lab1.{{ lab_base_domain_name }}"
      subnet_locations:
        - "{{ lab_location_name }}"
        - "Default Location"
      subnet_organizations:
        - "{{ lab_org_name }}"
        - "Default Organization"


###########################################################
# Foreman operating systems to attach the provisioning
# template to
########################################################### 
foreman_provisioning_template_operating_systems:
  - "Ubuntu Xenial"
  - "Ubuntu Bionic"
  - "RHEL 7"
  - "RHEL 8"

#############################################################
# List of puppet environment names to use for provisioning.
# These will be tied to the default and lab org & loc.
#############################################################
puppet_environment_names:
  - "labdev"
  - "labtest"
  - "labprod"


