---

# mnaio variables for OSA only
base_images:
  - image_name: "Ubuntu18.04.qcow2"
    mnaio_version: "stable/train"
    url: https://cloud-images.ubuntu.com/releases/bionic/release/ubuntu-18.04-server-cloudimg-amd64.img
    checksum: sha256:aa134bb2960ccacbbd1025fffbb0e2acdc9ee265498bbbcefd067326f8316a9f
    #checksum: sha256:4c62247baa2e8c480a924ff9dfa6f56f86f848f2477d3f7d36c532af6bdf0907
    user_data: true
    username: "ubuntu"
    operatingsystem: "Ubuntu Bionic"
    architecture: "x86_64"
    
  - image_name: "Ubuntu16.04.qcow2"
    mnaio_version: "stable/queens"
    url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    checksum: sha256:d04e0bc7b051ac05a0fec5931906109782462f2c415e1d306ff28f2ec9c9bbcd
    user_data: true
    username: "ubuntu"
    operatingsystem: "Ubuntu Xenial"
    architecture: "x86_64"


##################################################################
# Info for compute profiles
# These map out flavors to images along with some other settings
# to make provisioning easier. These values were pulled from
# the db after utilizing the GUI to set them.
##################################################################
compute_profile_image_id: "/var/lib/libvirt/images/Ubuntu18.04.qcow2"
compute_profile_suffix: "ubuntu-bionic"
foreman_compute_profiles:
  - name: "osa-infra-{{ compute_profile_suffix }}"
    compute_attributes: 
      - compute_resource: "libvirt-mnaio"
        vm_attrs:
          cpus: "12"
          cpu_mode: "default"
          memory: "17179869184"     # 16384 x 1024 x 1024
          image_id: "{{ compute_profile_image_id }}"
          nics_attributes:
            1:
              type: "network"
              network: "provisioning"
              bridge: ""
              model: "virtio"
            2:
              type: "network"
              network: "trunk"
              bridge: ""
              model: "virtio"
          volumes_attributes:
            0:
              pool_name: "images"
              capacity: "16G"
              allocation: "0G"
              format_type: "qcow2"
            1:
              pool_name: "images"
              capacity: "90G"
              allocation: "0G"
              format_type: "qcow2"
  - name: "osa-compute-{{ compute_profile_suffix }}"
    compute_attributes: 
      - compute_resource: "libvirt-mnaio"
        vm_attrs:
          cpus: "8"
          cpu_mode: "host-passthrough"
          memory: "17179869184"     # 16384 x 1024 x 1024
          image_id: "{{ compute_profile_image_id }}"
          nics_attributes:
            1:
              type: "network"
              network: "provisioning"
              bridge: ""
              model: "virtio"
            2:
              type: "network"
              network: "trunk"
              bridge: ""
              model: "virtio"
          volumes_attributes:
            0:
              pool_name: "images"
              capacity: "8G"
              allocation: "0G"
              format_type: "qcow2"
            1:
              pool_name: "images"
              capacity: "90G"
              allocation: "0G"
              format_type: "qcow2"
  - name: "osa-loadbalancer-{{ compute_profile_suffix }}"
    compute_attributes: 
      - compute_resource: "libvirt-mnaio"
        vm_attrs:
          cpus: "8"
          cpu_mode: "default"
          memory: "2147483648"     # 2048 x 1024 x 1024
          image_id: "{{ compute_profile_image_id }}"
          nics_attributes:
            1:
              type: "network"
              network: "provisioning"
              bridge: ""
              model: "virtio"
            2:
              type: "network"
              network: "trunk"
              bridge: ""
              model: "virtio"
          volumes_attributes:
            0:
              pool_name: "images"
              capacity: "50G"
              allocation: "0G"
              format_type: "qcow2"
  - name: "osa-cinder-{{ compute_profile_suffix }}"
    compute_attributes: 
      - compute_resource: "libvirt-mnaio"
        vm_attrs:
          cpus: "8"
          cpu_mode: "default"
          memory: "2147483648"     # 2048 x 1024 x 1024
          image_id: "{{ compute_profile_image_id }}"
          nics_attributes:
            1:
              type: "network"
              network: "provisioning"
              bridge: ""
              model: "virtio"
            2:
              type: "network"
              network: "trunk"
              bridge: ""
              model: "virtio"
          volumes_attributes:
            0:
              pool_name: "images"
              capacity: "16G"
              allocation: "0G"
              format_type: "qcow2"
            1:
              pool_name: "images"
              capacity: "90G"
              allocation: "0G"
              format_type: "qcow2"
            2:
              pool_name: "images"
              capacity: "60G"
              allocation: "0G"
              format_type: "qcow2"
  - name: "osa-swift-{{ compute_profile_suffix }}"
    compute_attributes: 
      - compute_resource: "libvirt-mnaio"
        vm_attrs:
          cpus: "8"
          cpu_mode: "default"
          memory: "2147483648"     # 2048 x 1024 x 1024
          image_id: "{{ compute_profile_image_id }}"
          nics_attributes:
            1:
              type: "network"
              network: "provisioning"
              bridge: ""
              model: "virtio"
            2:
              type: "network"
              network: "trunk"
              bridge: ""
              model: "virtio"
          volumes_attributes:
            0:
              pool_name: "images"
              capacity: "16G"
              allocation: "0G"
              format_type: "qcow2"
            1:
              pool_name: "images"
              capacity: "90G"
              allocation: "0G"
              format_type: "qcow2"
            2:
              pool_name: "images"
              capacity: "4G"
              allocation: "0G"
              format_type: "qcow2"
            3:
              pool_name: "images"
              capacity: "4G"
              allocation: "0G"
              format_type: "qcow2"
            4:
              pool_name: "images"
              capacity: "4G"
              allocation: "0G"
              format_type: "qcow2"
  - name: "osa-ceph-{{ compute_profile_suffix }}"
    compute_attributes: 
      - compute_resource: "libvirt-mnaio"
        vm_attrs:
          cpus: "2"
          cpu_mode: "default"
          memory: "1073741824"     # 1024 x 1024 x 1024
          image_id: "{{ compute_profile_image_id }}"
          nics_attributes:
            1:
              type: "network"
              network: "provisioning"
              bridge: ""
              model: "virtio"
            2:
              type: "network"
              network: "trunk"
              bridge: ""
              model: "virtio"
            3:
              type: "network"
              network: "storagerepl"
              bridge: ""
              model: "virtio"
          volumes_attributes:
            0:
              pool_name: "images"
              capacity: "16G"
              allocation: "0G"
              format_type: "qcow2"
            1:
              pool_name: "images"
              capacity: "90G"
              allocation: "0G"
              format_type: "qcow2"
            2:
              pool_name: "images"
              capacity: "5G"
              allocation: "0G"
              format_type: "qcow2"
            3:
              pool_name: "images"
              capacity: "5G"
              allocation: "0G"
              format_type: "qcow2"
            4:
              pool_name: "images"
              capacity: "5G"
              allocation: "0G"
              format_type: "qcow2"
            5:
              pool_name: "images"
              capacity: "20G"
              allocation: "0G"
              format_type: "qcow2"
            6:
              pool_name: "images"
              capacity: "20G"
              allocation: "0G"
              format_type: "qcow2"
            7:
              pool_name: "images"
              capacity: "20G"
              allocation: "0G"
              format_type: "qcow2"
  - name: "osa-ironic-{{ compute_profile_suffix }}"
    compute_attributes: 
      - compute_resource: "libvirt-mnaio"
        vm_attrs:
          cpus: "2"
          cpu_mode: "default"
          memory: "1073741824"     # 1024 x 1024 x 1024
          image_id: "{{ compute_profile_image_id }}"
          nics_attributes:
            1:
              type: "network"
              network: "provisioning"
              bridge: ""
              model: "virtio"
          volumes_attributes:
            0:
              pool_name: "images"
              capacity: "8G"
              allocation: "0G"
              format_type: "qcow2"
  - name: "osa-logging-{{ compute_profile_suffix }}"
    compute_attributes: 
      - compute_resource: "libvirt-mnaio"
        vm_attrs:
          cpus: "8"
          cpu_mode: "default"
          memory: "4294967296"     # 4096 x 1024 x 1024
          image_id: "{{ compute_profile_image_id }}"
          nics_attributes:
            1:
              type: "network"
              network: "provisioning"
              bridge: ""
              model: "virtio"
            2:
              type: "network"
              network: "trunk"
              bridge: ""
              model: "virtio"
          volumes_attributes:
            0:
              pool_name: "images"
              capacity: "16G"
              allocation: "0G"
              format_type: "qcow2"
            1:
              pool_name: "images"
              capacity: "90G"
              allocation: "0G"
              format_type: "qcow2"


##########################################################
# We will create some host groups to map to various roles
# being tested in the labs here.
##########################################################
operatingsystem: "Ubuntu Bionic"
host_groups:
  - name: "osa-infra-{{ compute_profile_suffix }}"
    architecture: "x86_64"
    operatingsystem: "{{ operatingsystem }}"
    description: "OSA infra node on kvm vm running ubuntu"
    compute_profile: "osa-infra-{{ compute_profile_suffix }}"
    compute_resource: "libvirt-mnaio"
    environment: "labprod"
    puppet_proxy: "{{ ansible_fqdn }}"
    puppet_ca_proxy: "{{ ansible_fqdn }}"
    organizations:
      - '{{ lab_org_name }}'
    locations:
      - '{{ lab_location_name }}'
    root_pass: "{{ instance_admin_pass }}"
  - name: "osa-compute-{{ compute_profile_suffix }}"
    architecture: "x86_64"
    operatingsystem: "{{ operatingsystem }}"
    description: "OSA compute node on kvm vm running ubuntu"
    compute_profile: "osa-compute-{{ compute_profile_suffix }}"
    compute_resource: "libvirt-mnaio"
    environment: "labprod"
    puppet_proxy: "{{ ansible_fqdn }}"
    puppet_ca_proxy: "{{ ansible_fqdn }}"
    organizations:
      - '{{ lab_org_name }}'
    locations:
      - '{{ lab_location_name }}'
    root_pass: "{{ instance_admin_pass }}"
  - name: "osa-loadbalancer-{{ compute_profile_suffix }}"
    architecture: "x86_64"
    operatingsystem: "{{ operatingsystem }}"
    description: "OSA loadbalancer node on kvm vm running ubuntu"
    compute_profile: "osa-loadbalancer-{{ compute_profile_suffix }}"
    compute_resource: "libvirt-mnaio"
    environment: "labprod"
    puppet_proxy: "{{ ansible_fqdn }}"
    puppet_ca_proxy: "{{ ansible_fqdn }}"
    organizations:
      - '{{ lab_org_name }}'
    locations:
      - '{{ lab_location_name }}'
    root_pass: "{{ instance_admin_pass }}"
  - name: "osa-swift-{{ compute_profile_suffix }}"
    architecture: "x86_64"
    operatingsystem: "{{ operatingsystem }}"
    description: "OSA swift node on kvm vm running ubuntu"
    compute_profile: "osa-swift-{{ compute_profile_suffix }}"
    compute_resource: "libvirt-mnaio"
    environment: "labprod"
    puppet_proxy: "{{ ansible_fqdn }}"
    puppet_ca_proxy: "{{ ansible_fqdn }}"
    organizations:
      - '{{ lab_org_name }}'
    locations:
      - '{{ lab_location_name }}'
    root_pass: "{{ instance_admin_pass }}"
  - name: "osa-cinder-{{ compute_profile_suffix }}"
    architecture: "x86_64"
    operatingsystem: "{{ operatingsystem }}"
    description: "OSA cinder node on kvm vm running ubuntu"
    compute_profile: "osa-cinder-{{ compute_profile_suffix }}"
    compute_resource: "libvirt-mnaio"
    environment: "labprod"
    puppet_proxy: "{{ ansible_fqdn }}"
    puppet_ca_proxy: "{{ ansible_fqdn }}"
    organizations:
      - '{{ lab_org_name }}'
    locations:
      - '{{ lab_location_name }}'
    root_pass: "{{ instance_admin_pass }}"
  - name: "osa-ceph-{{ compute_profile_suffix }}"
    architecture: "x86_64"
    operatingsystem: "{{ operatingsystem }}"
    description: "OSA ceph node on kvm vm running ubuntu"
    compute_profile: "osa-ceph-{{ compute_profile_suffix }}"
    compute_resource: "libvirt-mnaio"
    environment: "labprod"
    puppet_proxy: "{{ ansible_fqdn }}"
    puppet_ca_proxy: "{{ ansible_fqdn }}"
    organizations:
      - '{{ lab_org_name }}'
    locations:
      - '{{ lab_location_name }}'
    root_pass: "{{ instance_admin_pass }}"
  - name: "osa-ironic-{{ compute_profile_suffix }}"
    architecture: "x86_64"
    operatingsystem: "{{ operatingsystem }}"
    description: "OSA ironic node on kvm vm running ubuntu"
    compute_profile: "osa-ironic-{{ compute_profile_suffix }}"
    compute_resource: "libvirt-mnaio"
    environment: "labprod"
    puppet_proxy: "{{ ansible_fqdn }}"
    puppet_ca_proxy: "{{ ansible_fqdn }}"
    organizations:
      - '{{ lab_org_name }}'
    locations:
      - '{{ lab_location_name }}'
    root_pass: "{{ instance_admin_pass }}"
  - name: "osa-logging-{{ compute_profile_suffix }}"
    architecture: "x86_64"
    operatingsystem: "{{ operatingsystem }}"
    description: "OSA logging node on kvm vm running ubuntu"
    compute_profile: "osa-logging-{{ compute_profile_suffix }}"
    compute_resource: "libvirt-mnaio"
    environment: "labprod"
    puppet_proxy: "{{ ansible_fqdn }}"
    puppet_ca_proxy: "{{ ansible_fqdn }}"
    organizations:
      - '{{ lab_org_name }}'
    locations:
      - '{{ lab_location_name }}'
    root_pass: "{{ instance_admin_pass }}"

