---
- name: Create the keypair
  os_keypair:
    cloud: '{{ cloud }}'
    state: present
    validate_certs: no
    name: '{{ keypair }}'
  register: kpret

- name: Make sure the local keypair dir is created
  file:
    path: '{{ keypair_dir }}'
    state: directory
    mode: 0700

- name: Copy the private key over
  copy:
    dest: '{{ keypair_dir}}/{{ keypair }}'
    mode: 0400
    content: '{{ kpret.key.private_key }}'
  when: kpret.changed

- name: Copy the public key over
  copy:
    dest: '{{ keypair_dir}}/{{ keypair }}.pub'
    mode: 0644
    content: '{{ kpret.key.public_key }}'
  when: kpret.changed

- name: Create the flavor if it doesn't exist    
  os_nova_flavor:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    name: '{{ flavor }}'
    ram: '{{ flavor_ram }}'
    vcpus: '{{ flavor_vcpus }}'
    disk: '{{ flavor_disk }}'
    ephemeral: '{{ flavor_ephemeral }}'
    swap: '{{ flavor_swap }}'
    is_public: '{{ flavor_is_public }}'
    extra_specs: 
      "aggregate_instance_extra_specs:kvm": 'true'

- name: Create the vm
  os_server:
    state: present
    cloud: '{{ cloud }}'
    name: '{{ instance_name }}'
    key_name: '{{ keypair }}'
    image: '{{ image }}'
    flavor: '{{ flavor }}'
    network: '{{ network }}'
    validate_certs: no
    timeout: 200
    
- name: Get the instance info
  os_server_info:
    cloud: '{{ cloud }}'
    server: '{{ instance_name }}'
    validate_certs: no
  register: result

- name: Create a new volume
  os_volume:
    cloud: '{{ cloud }}'
    state: present
    validate_certs: no
    display_name: '{{ datadisk_name }}'
    size: '{{ datadisk_size }}'

- name: Attach the volume to the server
  os_server_volume:
    cloud: '{{ cloud }}'
    state: present
    validate_certs: no
    server: '{{ instance_name }}'
    volume: '{{ datadisk_name }}'
    device: '{{ datadisk_device }}'

- name: Add the new host to the inventory using instance_name
  add_host:
    hostname: '{{ instance_name }}'
    groups: katello_vms
    ansible_ssh_host: '{{ result.openstack_servers[0].accessIPv4 }}'
    ansible_ssh_user: centos
    ansible_ssh_private_key_file: '{{ keypair_dir }}/{{ keypair }}'

- name: Create a local inventory file for later use
  copy:
    dest: './inventory/katello_vms.ini'
    content: |
      [katello_vms]
      {{ instance_name }} ansible_ssh_host={{ result.openstack_servers[0].accessIPv4 }} ansible_ssh_user=centos ansible_ssh_private_key_file={{ keypair_dir }}/{{ keypair }}

- name: Create a vars file for use by forman playbooks later on
  copy:
    dest: './vars/katello-generated.yml'
    content: |
      # This file was auto generated by the katelo setup playbooks.
      # Don't edit by hand
      katello_host_ip: {{ result.openstack_servers[0].accessIPv4 }}
