---
#######################
# Foreman Related Prep
#######################
- name: Create a Organization to place labs in
  theforeman.foreman.organization:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    name: '{{ lab_org_name }}'
    state: present
  tags:
    - create_organization

- name: Create a Location in the new org to place labs in
  theforeman.foreman.location:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    name: '{{ lab_location_name }}'
    organizations:
      - '{{ lab_org_name }}'
  tags:
    - create_location

- name: Create foreman lab users
  theforeman.foreman.user:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    state: present
    login: '{{ item.username }}'
    user_password: '{{ item.password }}'
    mail: '{{ item.mail }}'
    admin: '{{ item.admin }}'
    default_organization: '{{ item.default_organization }}'
    default_location: '{{ item.default_location }}'
    description: '{{ item.description }}'
    firstname: '{{ item.firstname }}'
    lastname: '{{ item.lastname }}'
    locale: en
    auth_source: Internal
  with_items: '{{ foreman_users }}'
  tags:
    - create_users

- name: Create foreman domains
  theforeman.foreman.domain:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    state: present
    name: '{{ item.domain_name }}'
    description: '{{ item.domain_description }}'
    locations: '{{ item.domain_locations }}'
    organizations: '{{ item.domain_organizations }}'
    parameters: '{{ item.domain_parameters }}'
  with_items: '{{ static_labs }}'
  tags:
    - create_domains

- name: Create domain subnets
  theforeman.foreman.subnet:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    state: present
    name: '{{ item.1.subnet_name }}'
    boot_mode: '{{ item.1.subnet_bootmode }}'
    description: '{{ item.1.subnet_description }}'
    domains: 
      - '{{ item.0.domain_name }}'
    from_ip: '{{ item.1.subnet_dhcp_from }}'
    to_ip: '{{ item.1.subnet_dhcp_to }}'
    vlanid: '{{ item.1.subnet_vlan }}'
    gateway: '{{ item.1.subnet_gateway }}'
    ipam: '{{ item.1.subnet_ipam }}'
    mask: '{{ item.1.subnet_mask }}'
    network: '{{ item.1.subnet_network }}'
    network_type: '{{ item.1.subnet_type }}'
    locations: '{{ item.0.domain_locations }}'
    organizations: '{{ item.0.domain_organizations }}'
  with_subelements: 
    - '{{ static_labs }}'
    - domain_subnets
  tags:
    - create_subnets

- name: Create operating systems
  theforeman.foreman.operatingsystem:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    state: present
    architectures: '{{ item.architectures }}'
    description: '{{ item.description }}'
    family: '{{ item.family }}'
    major: '{{ item.major }}'
    minor: '{{ item.minor }}'
    name: '{{ item.name }}'
    password_hash: '{{ item.password_hash }}'
    release_name: '{{ item.release_name }}'
  with_items: '{{ foreman_operating_systems }}'
  tags:
    - create_operatingsystems

- name: Set safe_render mode to false to allow access to subnet parameters
  theforeman.foreman.setting:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    name: '{{ item.key }}'
    value: '{{ item.value }}'
  with_items: '{{ foreman_settings }}'
  tags:
    - update_foreman_settings

- name: Add the ip address as a global parameter to use for templating
  theforeman.foreman.global_parameter:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    state: present
    name: '{{ item.key }}'
    value: '{{ item.value }}'
  with_items: 
    - '{{ foreman_global_parameters }}'
    - '{{ additional_foreman_global_parameters }}'
  tags:
    - update_foreman_global_parameters
