---

# Include Foreman related prep tasks
- include: foreman_tasks.yml
  when: inventory_hostname == 'localhost'
  become: false
  tags:
    - foreman_tasks

# Include tasks to set up rackspace ca certificates on the katello host
- include: add_rackspace_ca_certs.yml
  when: "inventory_hostname != 'localhost' and foreman_compute_resources_openstack is defined"
  become: true
  tags:
    - add_rackspace_ca_certs

# Include Openstack related prep tasks
- include: openstack_tasks.yml
  when: "inventory_hostname == 'localhost' and foreman_compute_resources_openstack is defined"
  become: false
  tags:
    - openstack_tasks

# Include Foreman compute resource setup for openstack
- include: openstack_compute_resources.yml
  when: "inventory_hostname != 'localhost' and foreman_compute_resources_openstack is defined"
  become: true
  tags:
    - openstack_compute_resources

- include: libvirt_compute_resources.yml
  when: "inventory_hostname == 'localhost' and foreman_compute_resources_libvirt is defined"
  become: true
  tags:
    - libvirt_compute_resources

# Include Foreman related prep tasks
- include: provisioning_templates.yml
  when: inventory_hostname == 'localhost'
  become: false
  tags:
    - provisioning_templates

# Include Foreman related environment tasks
- include: provision_environments.yml
  when: inventory_hostname == 'localhost'
  become: false
  tags:
    - provision_environments

# Include Foreman related host group tasks
- include: provision_host_groups.yml
  when: inventory_hostname == 'localhost'
  become: false
  tags:
    - provision_host_groups
