---
- name: Create an openstack domain for the lab environments
  os_keystone_domain:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    name: '{{ openstack_domain_name }}'
    description: '{{ openstack_domain_desc }}'
  register: os_domain_ret

- name: Create an openstack project for the lab environments
  os_project:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    name: '{{ openstack_project_name }}'
    description: '{{ openstack_project_desc }}'
    domain_id: '{{ os_domain_ret.domain.id }}'
  register: os_project_ret

- name: Create the domain admin user
  os_user:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    name: '{{ openstack_project_admin_user }}'
    password: '{{ openstack_project_admin_pass }}'
    email: '{{ openstack_project_admin_email }}'
    description: '{{ openstack_project_admin_desc }}'
    domain: '{{ os_domain_ret.domain.id }}'
    default_project: '{{ os_project_ret.project.id }}'
  register: os_user_ret

- name: Set up labs admin as domain and project admin(can't be done with os_user_role at time of writing while setting the user domain)
  shell: |
    openstack --os-cloud '{{ cloud }}' role add --domain '{{ os_domain_ret.domain.id }}' --user-domain '{{ os_domain_ret.domain.id }}' --user '{{ os_user_ret.user.id }}' admin --insecure
    openstack --os-cloud '{{ cloud }}' role add --project '{{ os_project_ret.project.id }}' --user-domain '{{ os_domain_ret.domain.id }}' --user '{{ os_user_ret.user.id }}' admin --insecure

- name: Set the project quotas
  os_quota:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    name: '{{ os_project_ret.project.id }}'
    ram: '-1'
    instances: '-1'
    cores: '-1'
    floating_ips: '-1'
    gigabytes: '-1'
    
- name: Open up the icmp for the labs
  os_security_group_rule:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    security_group: 'default'
    project: '{{ os_project_ret.project.id }}'
    direction: 'ingress'
    protocol: icmp
    
- name: Open up the all of tcp and udp for the labs
  os_security_group_rule:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    security_group: 'default'
    project: '{{ os_project_ret.project.id }}'
    direction: 'ingress'
    protocol: '{{ item }}'
    port_range_min: 1
    port_range_max: 65535
  with_items:
    - tcp
    - udp

