---
- name: Create an openstack project for the lab environments
  os_project:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    name: '{{ openstack_project_name }}'
    description: '{{ openstack_project_desc }}'
    domain: '{{ openstack_domain_name }}'
  register: os_project_ret
  tags:
    - create_openstack_project

- name: Create the project admin user
  os_user:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    name: '{{ openstack_project_admin_user }}'
    password: '{{ openstack_project_admin_pass }}'
    email: '{{ openstack_project_admin_email }}'
    description: '{{ openstack_project_admin_desc }}'
    domain: '{{ openstack_domain_name }}'
    default_project: '{{ os_project_ret.project.id }}'
  register: os_user_ret
  tags:
    - create_user

- name: Set up labs-admin as admin under domain (os_user_role is broken with domain addition)
  shell: openstack --os-cloud '{{ cloud }}' role add --domain '{{ openstack_domain_name }}' --user '{{ os_user_ret.user.id }}' admin --insecure
  tags:
    - add_user_roles

- name: Set up labs-admin as admin under project 
  os_user_role:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    user: '{{ os_user_ret.user.id }}'
    role: "admin"
    project: '{{ openstack_project_name }}'
  tags:
    - add_user_roles
    
- name: Set the project quotas
  os_quota:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    name: '{{ os_project_ret.project.id }}'
    ram: '-1'
    instances: '-1'
    cores: '-1'
    floating_ips: '-1'
    gigabytes: '-1'
  tags:
    - update_project_quotas
    
- name: Open up the icmp for the labs
  os_security_group_rule:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    security_group: 'default'
    project: '{{ os_project_ret.project.id }}'
    direction: 'ingress'
    protocol: icmp
  tags:
    - update_project_security_groups
    
- name: Open up the all of tcp and udp for the labs
  os_security_group_rule:
    state: present
    cloud: '{{ cloud }}'
    validate_certs: no
    security_group: 'default'
    project: '{{ os_project_ret.project.id }}'
    direction: 'ingress'
    protocol: '{{ item }}'
    port_range_min: 1
    port_range_max: 65535
  with_items:
    - tcp
    - udp
  tags:
    - update_project_security_groups

