- name: Upload the default userdata templates
  theforeman.foreman.provisioning_template:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    state: present
    name: "{{ item }}"
    file_name: "{{ provisioning_template_path }}/{{ item }}.erb"
    operatingsystems: '{{ foreman_provisioning_template_operating_systems }}'
    locations:
      - "Default Location"
      - '{{ lab_location_name }}'
    organizations:
      - "Default Organization"
      - '{{ lab_org_name }}'
  loop:
    - "custom-libvirt-mnaio-userdata"
    - "custom-baremetal-userdata"
  tags:
    - configure_provisioning_templates


- name: Associate the userdata template as the default for the list of operating systems.
  theforeman.foreman.os_default_template:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    state: present
    operatingsystem: '{{ item.1 }}'
    template_kind: "user_data"
    provisioning_template: "{{ item.0 }}"
  loop: "{{ ['custom-baremetal-userdata'] |product(foreman_provisioning_template_operating_systems)|list }}"
  when: 'foreman_compute_resources_openstack is defined'
  tags:
    - configure_provisioning_templates

- name: Associate the userdata template as the default for the list of operating systems.
  theforeman.foreman.os_default_template:
    validate_certs: no
    username: '{{ foreman_username }}'
    password: '{{ foreman_password }}'
    server_url: '{{ foreman_url }}'
    state: present
    operatingsystem: '{{ item.1 }}'
    template_kind: "user_data"
    provisioning_template: "{{ item.0 }}"
  loop: "{{ ['custom-libvirt-mnaio-userdata'] |product(foreman_provisioning_template_operating_systems)|list }}"
  when: 'foreman_compute_resources_libvirt is defined'
  tags:
    - configure_provisioning_templates
