---

- name: Prep the katello and openstack environments for labs
  hosts: 'katello_vms:localhost'
  vars_files:
    - vars/katello-generated.yml
    - vars/forklift.yml
    - vars/lab_prep.yml
  pre_tasks:
    - name: Gather some facts to use for the forman modules
      set_fact:
        foreman_username: 'admin'
        foreman_password: '{{ foreman_installer_admin_password }}'
        foreman_url: 'https://{{ katello_host_ip }}'
      tags:
        - always
      delegate_to: localhost
  roles:
    - prep_lab_environment

