---
- name: Set up a test katello vm
  hosts: localhost
  connection: local
  tags:
    - create_katello_vm
  roles:
    - create_katello_vm

- name: Configure the vm after deployment
  hosts: katello_vms
  become: true
  tags:
    - configure_katello
  roles:
    - fix_hosts_file
    - configure_katello_vm_disks

